packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  argon2: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
nodeLinker: hoisted
overrides:
  "glob": "^13.0.6"
  "inflight": "-"
  "uuid@<9.0.0": "^11.0.1"
